# baseURL = "http://example.org/"
# languageCode = "en-us"
# title = "My New Hugo Site"
# theme = "creative"
baseurl = "https://muuuuuuuuuu.github.io/Myproject"
languageCode = "en-us"
title = "muuuuuuuuuuのPortfolio Site"
theme = "hugo-creative-theme"
googleAnalytics = ""
publishDir = "docs"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "mmm.ico"


	# Navigation
	[params.navigation]
		brand = "MUUUUUUUUUU PORTFOLIO SITE"

		[params.navigation.links]
			about     = "PROFILE"
			services  = "STUDY"
			portfolio = "EXPERIENCE"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "SELF<br>INTRODUCTION"
		subtitle   = "初めまして！今プログラミングの勉強をしています。主にRubyとrailsの勉強をしています。まだまだ未熟者ですが宜しくお願い致します。"

		# "[Lorem](//google.com)"

		buttonText = "もっと見て貰えると嬉しいです！"


	# About section
	[params.about]
		headline    = "PROFILE"
		description = "・中村勝也、32歳(61.1.6)、A型、趣味・映画鑑賞・歩く・走る・筋トレ<br><br>・好きなことわざ、虎穴に入らずんば虎子を得ず！、思い立ったが吉日 ならばその日以降は全て凶日！<br><br>・前職は工場勤務9年(班長をしていました)<br><br>・ある日You Tubeでプログラミンに関する動画をみる<br>プログラミングに興味を持ちその日からプログラミング、ITの事を色々調べ、これやっ！って思い1週間後にMac Book Proを購入<br>そしてすぐにプログラミング教室に入塾！勉強に集中したくて2ヶ月後に退社。<br>思ってたより10倍ぐらい難しいが、分からない事を解決出来た時の達成感が<br>今まで仕事をしてきてこんな達成感を味わった事がなく半端なく嬉しい！！<br>1年後の自分にワクワクしながら今も毎日勉強してます！！<br><br>・日々勉強！日々努力！日々成長！この気持ちを忘れずに生きて行きます！！<br><br>"


			# [Lorem](//google.com)グーグルに飛べるコード
		# buttonText  = "TOP"


	# Service section
	[params.services]
		headline = "I have been studying"

        [[params.services.list]]
            # icon = "fa-diamond"
            title = "言語"
            description = "Ruby"

        [[params.services.list]]
			# icon = "fa-paper-plane"
			title = "フレームワーク"
			description = "Ruby on Rails"

		[[params.services.list]]
            # icon = "fa-newspaper-o"
            title = "バージョン管理"
            description = "Github,Bitbucket"

        [[params.services.list]]
            # icon = "fa-heart"
            title = "エディタ"
            description = "Atom"

			  # [[params.services.list]]
        #     # icon = "fa-heart"
        #     title = "インフラ"
        #     description = "AWS"

			  # [[params.services.list]]
        #     # icon = "fa-heart"
        #     title = "データベース"
        #     description = "SQLite"

			  [[params.services.list]]
            # icon = "fa-heart"
            title = "etc.."
            description = "MacOS,HEROKU,Linux,AWSs3,SQlite,ターミナル,Qiita,hugo,Word,Excel"

				[[params.services.list]]
            # icon = "fa-heart"
            title = "study"
            description = "プロゲート(HTML,CSS,Ruby,JS,Ruby on Rails,Python,PHP,Command Line,Git,Sass)ドットインストール(基礎全般) Ruby on Railsチュートリアル yukicoder(星1から2) etc.."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		# headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			# text = "Download now"
			# text = "Download now"
			# link = "//github.com/digitalcraftsman/hugo-creative-theme"
			# link = "https://twitter.com/muuuuuuuuuu7"

	# Contact section
	[params.contact]
		headline = "CONTACT"
		description = ""
		phone = ""
		email = "muuuuu10uuuuu@icloud.com"

		# [params.social]
    # icon = "twitter"
    # icon_pack = "fab"
    # link = "https://twitter.com/muuuuuuuuuu7"



	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
